### ISSUE TITLE
Enhancement: apply additonal metadata 

### ISSUE THREAD

**Issue by thatChadM** [Shawson/Playnite-OculusLibrary#13]
During the import process the launch path executable is found and recorded, but the installation directory is left blank.  Should be able to infer the installation directory by trimming the executable name from the launch path executable.

It's a minor issue, and I only noticed because I was trying to clean up duplicate entries from earlier versions of the library.  Trying to use the filtering to find the duplicates was problematic due to a bug in Playnite (clicking Playnite for the library returns no items) and one option I tried was to sort on installation directory since I couldn't sort on the executable path.

I finally managed to find the duplicates by doing a Group by library, and then deleting all items in the Playnite library.  Apparently Playnite will assign any item in the library to the Playnite library if the original importing library extension is disabled.  In other words, Oculus extension imports to Oculus library. Disable the Oculus extension and now all the items that were in the Oculus library are now considered to be in the Playnite library, although only when using Group by library; the filter by library option returns no items when the Playnite library is selected.

**Comment by Shawson** [comment]
I agree, it should be doing this anyway!  I'll sort that
